<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Candidate;
use Illuminate\Support\Str;

class CandidateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $candidates = [
            [
                'nik' => '3209302903200002',
                'nama_lengkap' => 'AHMAD SABILUL MUHTADIN',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2020-03-29',
                'jenis_kelamin' => 'LAKI-LAKI',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '341',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3217113112190002',
                'nama_lengkap' => 'MUHAMMAD FARASH EL MALIQ',
                'tempat_lahir' => 'Bandung Barat',
                'tanggal_lahir' => '2019-12-31',
                'jenis_kelamin' => 'LAKI-LAKI',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '342',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209270702200003',
                'nama_lengkap' => 'GIBRAN RAFIF ATHARRAZKA',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2020-02-07',
                'jenis_kelamin' => 'LAKI-LAKI',
                'hasil_psikotes' => 'CUKUP RAGU-RAGU',
                'no_surat' => '343',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209245909190002',
                'nama_lengkap' => 'ALLEIRA LETISHA KHAIRINA',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2019-09-19',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '344',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209246207200001',
                'nama_lengkap' => 'HAYYA MAHIRA YUSUF',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2020-07-22',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '345',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209241806190001',
                'nama_lengkap' => 'RADEN MUHAMAD RAKMAT KARTAKUSUMA',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2019-06-18',
                'jenis_kelamin' => 'LAKI-LAKI',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '346',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209241505200003',
                'nama_lengkap' => 'QIAN ARFA IBRAHIM',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2020-05-15',
                'jenis_kelamin' => 'LAKI-LAKI',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '347',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209275710190001',
                'nama_lengkap' => 'QIONA AIZA HUMAIRA',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2019-10-17',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '348',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3175066402200016',
                'nama_lengkap' => 'ERLYTA ORLIN ALTHAFUNNISA',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2020-02-24',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '349',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209242204190002',
                'nama_lengkap' => 'MUHAMMAD SALMAN ALFARIZ',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2019-04-22',
                'jenis_kelamin' => 'LAKI-LAKI',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '350',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209241012190001',
                'nama_lengkap' => 'MANENDRA BANDISOHARI',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2019-12-10',
                'jenis_kelamin' => 'LAKI-LAKI',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '351',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209286506200001',
                'nama_lengkap' => 'DELIYA FIRLITA',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2020-06-25',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '352',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209172406190001',
                'nama_lengkap' => 'MUHAMMAD REZVAN SYAUQI',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2019-06-24',
                'jenis_kelamin' => 'LAKI-LAKI',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '353',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209175806200003',
                'nama_lengkap' => 'QUEENSHA AULIA PUTRI',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2020-06-18',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '354',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209256812190001',
                'nama_lengkap' => 'ARDELA ALTAMIRA VERDIYANA',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2019-12-28',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'CUKUP RAGU-RAGU',
                'no_surat' => '355',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209270801200002',
                'nama_lengkap' => 'AMMAR RANGGA ELFATIH',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2020-01-08',
                'jenis_kelamin' => 'LAKI-LAKI',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '356',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3274050209190002',
                'nama_lengkap' => 'MUHAMMAD YUSUF BAFAGIH',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2019-09-02',
                'jenis_kelamin' => 'LAKI-LAKI',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '357',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209285412190001',
                'nama_lengkap' => 'AYRA ANINDYA AZZAHRA',
                'tempat_lahir' => 'Depok',
                'tanggal_lahir' => '2019-12-14',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '358',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209174507190002',
                'nama_lengkap' => 'INARA PUTRI AZZAHRA',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2019-07-05',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '359',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209255602200001',
                'nama_lengkap' => 'SHEILA NUR HUSEIN',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2020-02-16',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '360',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209260203200002',
                'nama_lengkap' => 'QIYAS ABDAB SYABIL',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2020-03-02',
                'jenis_kelamin' => 'LAKI-LAKI',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '361',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209290501200002',
                'nama_lengkap' => 'MUHAMMAD ASHFA NAFIDZUL HAQ',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2019-01-05',
                'jenis_kelamin' => 'LAKI-LAKI',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '362',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209241506200001',
                'nama_lengkap' => 'MUHAMMAD ZAIN HAMIZAN',
                'tempat_lahir' => 'Karawang',
                'tanggal_lahir' => '2020-06-15',
                'jenis_kelamin' => 'LAKI-LAKI',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '363',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209240904190001',
                'nama_lengkap' => 'AHMAD HOSEIN MORTADZA ALKAFF',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2019-04-09',
                'jenis_kelamin' => 'LAKI-LAKI',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '364',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209276905200001',
                'nama_lengkap' => 'GENDIS HANIN HANANIA',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2020-05-29',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '365',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209240803190002',
                'nama_lengkap' => 'NAFISA IZZATUL MAARIF',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2019-03-08',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '366',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209271812190001',
                'nama_lengkap' => 'MOKHAMMAD IRSYAD MAULANA IMAN',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2019-12-18',
                'jenis_kelamin' => 'LAKI-LAKI',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '367',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209246301200002',
                'nama_lengkap' => 'HAFLA SHANUM DYKHA',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2020-01-23',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '368',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209245003200002',
                'nama_lengkap' => 'SYAHILA AZZAHRA',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2020-03-10',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '369',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3673056508190002',
                'nama_lengkap' => 'FATHIA ARSYILA',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2019-08-25',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '370',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209246304190001',
                'nama_lengkap' => 'ARINY NUR SYAMSAH',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2019-04-23',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '371',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209244411190003',
                'nama_lengkap' => 'SILFY YAWMIL MAULIDIYYAH',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2019-11-04',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '372',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209296009200001',
                'nama_lengkap' => 'NASHA RAZETTA ZUNAIRA',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2020-09-20',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '373',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209296909200001',
                'nama_lengkap' => 'FATHIYA SHANUM RAHADYAN',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2020-09-29',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '374',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3274041506200003',
                'nama_lengkap' => 'NADHIF ZAKI MIRZA',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2020-06-15',
                'jenis_kelamin' => 'LAKI-LAKI',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '375',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209240909190002',
                'nama_lengkap' => 'FAWAS AL FADILAH',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2019-09-09',
                'jenis_kelamin' => 'LAKI-LAKI',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '376',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209285605190001',
                'nama_lengkap' => 'SITI NURRIZQOTUL RAMADHANIYAH',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2019-05-16',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'CUKUP RAGU-RAGU',
                'no_surat' => '377',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209242604200001',
                'nama_lengkap' => 'KAIVANDRA ZAVIER HAFIZ',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2020-04-26',
                'jenis_kelamin' => 'LAKI-LAKI',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '378',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209274810190001',
                'nama_lengkap' => 'HANANIA ALISHA',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2019-10-08',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '379',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '1234567890123456',
                'nama_lengkap' => 'GANIYAH ADZKADINA SETIAWAN',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2020-07-01',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '380',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209250804200002',
                'nama_lengkap' => 'ALVINO DAFFA MUWAFFAQ',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2020-04-08',
                'jenis_kelamin' => 'LAKI-LAKI',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '381',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209242509190003',
                'nama_lengkap' => 'MUHAMMAD FATAN AL-FAREZY',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2019-09-25',
                'jenis_kelamin' => 'LAKI-LAKI',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '382',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209245306200006',
                'nama_lengkap' => 'AISYAH NADHIRA MILLEA',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2020-06-13',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '383',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209242005200001',
                'nama_lengkap' => 'ARTA PRAWIRA RAHARJA',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2020-05-20',
                'jenis_kelamin' => 'LAKI-LAKI',
                'hasil_psikotes' => 'CUKUP RAGU-RAGU',
                'no_surat' => '384',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209280307190001',
                'nama_lengkap' => 'MUHAMMAD IDRIS',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2019-07-03',
                'jenis_kelamin' => 'LAKI-LAKI',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '385',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209172011190001',
                'nama_lengkap' => 'MUHAMMAD ZUBAIR HAFIDZAHULLAH',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2019-11-20',
                'jenis_kelamin' => 'LAKI-LAKI',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '386',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209254903200001',
                'nama_lengkap' => 'AINA HUMAIRA SUPRIANTORO',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2020-03-09',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '387',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3274035710200003',
                'nama_lengkap' => 'HAFIDZAH GHANIA NUR PUTRI RAMADHANI',
                'tempat_lahir' => 'Kota Cirebon',
                'tanggal_lahir' => '2020-10-17',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '388',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209271202200002',
                'nama_lengkap' => 'MUHAMMAD RAIHAN AKBAR HILMI',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2020-02-12',
                'jenis_kelamin' => 'LAKI-LAKI',
                'hasil_psikotes' => 'CUKUP RAGU-RAGU',
                'no_surat' => '389',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3172044103200013',
                'nama_lengkap' => 'ALISHA ABDILLA ZAHRA',
                'tempat_lahir' => 'Bekasi',
                'tanggal_lahir' => '2020-03-01',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '390',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209247112190005',
                'nama_lengkap' => 'FAHIRA IMANIAR PUTRI',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2019-12-31',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'CUKUP RAGU-RAGU',
                'no_surat' => '391',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '1234567891234567',
                'nama_lengkap' => 'DHEFIN EL FATIH',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2019-06-10',
                'jenis_kelamin' => 'LAKI-LAKI',
                'hasil_psikotes' => 'CUKUP RAGU-RAGU',
                'no_surat' => '392',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209282609200001',
                'nama_lengkap' => 'MUHAMMAD GASENDRA FAYEDH SABIQ',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2020-09-26',
                'jenis_kelamin' => 'LAKI-LAKI',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '393',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209294712190003',
                'nama_lengkap' => 'NIKEN SEKAR KEDATHON ANTONI',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2019-12-07',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '394',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209241006200001',
                'nama_lengkap' => 'NAHEL DZU AZRI MUHAMMAD',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2020-06-10',
                'jenis_kelamin' => 'LAKI-LAKI',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '395',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3209256305200002',
                'nama_lengkap' => 'AFIQAH NAHDA',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2020-05-23',
                'jenis_kelamin' => 'PEREMPUAN',
                'hasil_psikotes' => 'SIAP',
                'no_surat' => '396',
                'kode_verifikasi' => Str::random(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Karena datanya berbentuk array multi-dimensi, kita bisa melakukan insert batch
        Candidate::insert($candidates);
    }
}